### ISSUE TITLE
When marking text, the quote button is getting placed not where it should be

### ISSUE THREAD

**Issue by halberfan** [darkpixlz/DarkPixlz-s-Modern-Theme#3]
![grafik](https://user-images.githubusercontent.com/39102685/221780309-ddaed4fd-85b9-4062-b980-cb65cf91c1c6.png)
Sorry that it's german :D But yeah, I think u can see what the problem is nonetheless. 

I've tried fixing it myself, but it didn't work out. It seems like it has something to do with the blur effect of the background. When you disable it, it works perfectly fine. I don't know what you can do to avoid it tho.

**Comment by pyxfluff** [comment]
Thanks, I'll get this fixed.
