### ISSUE TITLE
Menu Background Fully Transparent

### ISSUE THREAD

**Issue by MWG-Logan** [darkpixlz/DarkPixlz-s-Modern-Theme#4]
Hello!
I posted briefly about this on the forums, but I feel it should probably be handled properly here.
https://meta.discourse.org/t/darkpixlzs-modern-theme/232543/67?u=mwgmorningwood

I'm running into an issue where my menu (header menu instead of sidebar and user menu both) has 1 opacity, but a background-color value that has max transparency.
This is happening when using the default dark color palette with only the accent colors edited. It looks like this checkbox is what's doing it:

![image](https://user-images.githubusercontent.com/2997336/224860898-aea0be60-8f53-4780-97f2-618b14fa8f22.png)

Example of issue:
![image](https://user-images.githubusercontent.com/2997336/224861006-a6efb708-0a9d-444a-9cda-084dbdc41db9.png)

The second array here worries me as that's a max transparency value.
I'm quite the beginner with CSS so take that with a grain of salt

```
element.style {
    top: 100%;
    height: auto;
}
.menu-panel.drop-down {
    background-color: rgba(0,15,255,0);
    -webkit-backdrop-filter: blur(2rem);
    backdrop-filter: blur(2rem);
}
.menu-panel.drop-down {
    margin-top: 1em;
    border-radius: 0.5em;
    border: none;
}
.hamburger-panel .revamped {
    --d-sidebar-highlight-color: var(--highlight-medium);
    --d-sidebar-row-horizontal-padding: 0.5rem;
    --d-sidebar-row-height: 30px;
    --d-sidebar-row-horizontal-padding: 0.66rem;
    --d-sidebar-row-vertical-padding: 0.33rem;
}
.menu-panel.drop-down {
    position: absolute;
    top: 100%;
    right: -10px;
    max-height: 80vh;
}
.menu-panel {
    border: 1px solid var(--primary-low);
    box-shadow: 0 12px 12px rgb(0 0 0 / 15%);
    background-color: var(--secondary);
    z-index: 1000;
    padding: 0.5em;
    width: 320px;
    overflow: hidden;
    display: flex;
    flex-direction: column;
}
body, button, div, span, a, img, svg, h1, h2, h3, h4, h5, h6, p, summary, input, textbox, input, textarea, li, ul {
    font-family: "Nunito" !important;
}
```
![image](https://user-images.githubusercontent.com/2997336/224862083-7e4f8423-4739-4ec5-9ebe-703274d5a4c9.png)

**Comment by pyxfluff** [comment]
Thanks - will look into this.

The transparency is expected, I'm not sure why the blur does not appear on Chromium. I'll have a look, thanks!

**Comment by MWG-Logan** [comment]
Pretty repeatable, then? I can provide any details you'd need if not.

**Comment by pyxfluff** [comment]
Yep, seeing it on my site on Chromium.

**Comment by pyxfluff** [comment]
Just learned this this is a bit of a known issue on Chromium - I'll keep looking for a potential fix, or alert Google.
