### ISSUE TITLE
Sometimes flairs are placed at pretty weird positions

### ISSUE THREAD

**Issue by halberfan** [darkpixlz/DarkPixlz-s-Modern-Theme#5]
Sometimes flairs are placed at pretty weird positions:
![grafik](https://user-images.githubusercontent.com/39102685/228089922-ea26cdef-ee3e-4ccd-b3aa-5132d04d678d.png)
![grafik](https://user-images.githubusercontent.com/39102685/228089954-fbc06f6e-5d8a-4391-9d3d-41da9997b713.png)
But some work just fine as well:
![grafik](https://user-images.githubusercontent.com/39102685/228090006-1ea6f93d-0829-4e22-8de8-4bc035cb0b52.png)

**Comment by pyxfluff** [comment]
What browser are you using and what page is this on?

**Comment by halberfan** [comment]
I'm using Firefox and this is on https://forum.ftscraft.de/ 

Should I enable the theme so you can look? I took the screen on preview mode.

**Comment by halberfan** [comment]
Oh wait, it was my fault. I added a component which caused it. Sorryyy. After disabling it it works just fine.

**Comment by pyxfluff** [comment]
No worries! What's the component called (if available) so I can either look into it or add it to the list of dangerous components?

**Comment by halberfan** [comment]
It's one I made custom. But... now it is there again, even now, when the component isn't enabled anymore. So I guess it's something on the theme nevertheless. 

Right after disabling and refreshing the page it worked, now after refreshing it again and the component still being disabled, it got the same problem. 

I put the theme on as default so you can see it aswell. This is now without any components enabled. https://forum.ftscraft.de/

**Comment by pyxfluff** [comment]
Yep, I'm seeing it there, thanks for letting me know!
