### ISSUE TITLE
On the Latest-page profile pictures got a pretty bad resolution

### ISSUE THREAD

**Issue by halberfan** [darkpixlz/DarkPixlz-s-Modern-Theme#6]
e.g. in this picture
![grafik](https://user-images.githubusercontent.com/39102685/228090236-3e013e31-3012-45f2-8de1-2ee094c11b24.png)

**Comment by pyxfluff** [comment]
I remember there was a component which solved this, I'll look for it and bundle it with the theme.

**Comment by pyxfluff** [comment]
Use this component:
https://meta.discourse.org/t/avatar-size-and-shape/106124
I'll bundle it with the theme soon.
